global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: "docker-localhost"
    replica: "A"

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "rules/*.yml"

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "alertmanager"
    static_configs:
      - targets: ["alertmanager:9093"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  # Docker containers autodiscovery
  - job_name: "docker-containers"
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 10s
        port: 9090
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        regex: "/(.*)"
        target_label: container_name
        replacement: "$1"
      - source_labels:
          [__meta_docker_container_label_com_docker_compose_service]
        target_label: service_name
      - source_labels:
          [__meta_docker_container_label_com_docker_compose_project]
        target_label: project_name
      - source_labels: [__meta_docker_port_private_port]
        regex: "9[0-9]{3}"
        action: keep
      - source_labels: [__address__]
        regex: '([^:]+):\d+'
        target_label: __address__
        replacement: "${1}:9090"

  # Vault metrics (if running)
  - job_name: "vault"
    static_configs:
      - targets: ["localhost:8200"]
    metrics_path: "/v1/sys/metrics"
    params:
      format: ["prometheus"]
    scheme: https
    tls_config:
      insecure_skip_verify: true
    scrape_interval: 30s

  # Docker daemon metrics (native Docker metrics)
  - job_name: "docker-daemon"
    static_configs:
      - targets: ["host.docker.internal:9323"]
    scrape_interval: 15s
    metrics_path: "/metrics"
    scrape_timeout: 10s
