services:
  ollama:
    image: ollama/ollama:0.9.1
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
      - OLLAMA_ORIGINS=*
    networks:
      - ollama-network
    # Uncomment below for GPU support (NVIDIA)
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    ports:
      - "3000:8080"
    volumes:
      - open-webui-data:/app/backend/data
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_SECRET_KEY=your-secret-key-change-this
      - WEBUI_JWT_SECRET_KEY=your-jwt-secret-change-this
      - DATA_DIR=/app/backend/data
      - ENABLE_SIGNUP=true
      - DEFAULT_USER_ROLE=user
      - WEBUI_AUTH=true
    networks:
      - ollama-network
    depends_on:
      - ollama

networks:
  ollama-network:
    driver: bridge
    name: ollama-network

volumes:
  ollama-data:
    driver: local
  open-webui-data:
    driver: local