name: Checkov Security Scan

on:
  push:
    branches:
      - main
    tags:
      - 'v*'    
  pull_request:
    types:
      - opened
      - synchronize
      - reopened  
  workflow_dispatch: 

permissions:
  contents: read
  security-events: write # Permissão necessária para upload de SARIF

jobs:
  checkov-scan:
    name: Checkov Scan
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.10'

      - name: Install Checkov
        run: pip install checkov

      # Run Checkov with SARIF output
      - name: Run Checkov and generate SARIF report
        run: |
          checkov -d ./ \
            -o sarif \
            --output-file checkov-results.sarif \
            --quiet

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@181d5eefc20863364f96762470ba6f862bdef56b # v3.29.2
        with:
          sarif_file: checkov-results.sarif

      - name: Show Checkov results (verbose)
        run: checkov -d ./
